#!/usr/bin/env python3
"""Generate the radix-2^51 Ed25519 base-point table used by X25519."""

from __future__ import annotations

import hashlib
import sys


MODULUS = (1 << 255) - 19
MASK_51 = (1 << 51) - 1
EDWARDS_D = (-121665 * pow(121666, MODULUS - 2, MODULUS)) % MODULUS
EDWARDS_TWO_D = (2 * EDWARDS_D) % MODULUS
BASE_X = int.from_bytes(
    bytes.fromhex("1ad5258f602d56c9b2a7259560c72c695cdcd6fd31e2a4c0fe536ecdd3366921"),
    "little",
)
BASE_Y = (4 * pow(5, MODULUS - 2, MODULUS)) % MODULUS


def add(
    lhs: tuple[int, int],
    rhs: tuple[int, int],
) -> tuple[int, int]:
    x1, y1 = lhs
    x2, y2 = rhs
    product = (EDWARDS_D * x1 * x2 * y1 * y2) % MODULUS
    x = ((x1 * y2 + y1 * x2) * pow(1 + product, MODULUS - 2, MODULUS)) % MODULUS
    y = ((y1 * y2 + x1 * x2) * pow(1 - product, MODULUS - 2, MODULUS)) % MODULUS
    return x, y


def limbs(value: int) -> list[int]:
    return [(value >> (51 * index)) & MASK_51 for index in range(5)]


def generate() -> list[int]:
    table: list[int] = []
    position_base = (BASE_X, BASE_Y)
    for _ in range(32):
        multiple = position_base
        for _ in range(8):
            x, y = multiple
            table.extend(limbs((y + x) % MODULUS))
            table.extend(limbs((y - x) % MODULUS))
            table.extend(limbs((EDWARDS_TWO_D * x * y) % MODULUS))
            multiple = add(multiple, position_base)
        for _ in range(8):
            position_base = add(position_base, position_base)
    return table


def render(table: list[int]) -> str:
    payload = b"".join(value.to_bytes(8, "little") for value in table)
    digest = hashlib.sha256(payload).hexdigest()
    lines = [
        "// Generated by Tools/generate_x25519_basepoint_table.py.",
        "// The values are mathematical constants for (j + 1) * 256^i * B.",
        f"// Radix-2^51 limb payload SHA-256: {digest}",
        "",
        "enum X25519BasepointTable {",
        "    static let limbs: ContiguousArray<UInt64> = [",
    ]
    for offset in range(0, len(table), 5):
        values = ", ".join(str(value) for value in table[offset : offset + 5])
        lines.append(f"        {values},")
    lines.extend(["    ]", "}", ""])
    return "\n".join(lines)


def main() -> None:
    table = generate()
    if len(table) != 32 * 8 * 3 * 5:
        raise RuntimeError("unexpected X25519 base-point table size")
    sys.stdout.write(render(table))


if __name__ == "__main__":
    main()
